#! /bin/bash

# 256 color
for row in `seq 0 15`
do
	for col in `seq 0 15`
	do
		color_num=$((16*$row+$col))
		if test $color_num -lt 10
		then
			blank="   "
		elif test $color_num -lt 100
		then
			blank="  "
		else
			blank=" "
		fi
		echo -ne "\033[1;38;5;${color_num}m${blank}${color_num}"
	done
	echo ''
done

